on: push
name: Detect unmergeable PRs
jobs:
  detect_unmergeable_pull_request_and_mark_them:
    runs-on: ubuntu-latest
    steps:
    - name: detect_unmergeable_pull_request_and_mark_them
      uses: cats-oss/github-action-detect-unmergeable@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
